"""create persona table

Revision ID: b49a5b4f90da
Revises: 12f67f959a4f
Create Date: 2026-07-20 13:31:15.483521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b49a5b4f90da'
down_revision: Union[str, Sequence[str], None] = '12f67f959a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('nombre', sa.String(), nullable=False))
    op.add_column('personas', sa.Column('apellido', sa.String(), nullable=False))
    op.add_column('personas', sa.Column('email', sa.String(), nullable=False))
    op.create_index(op.f('ix_personas_email'), 'personas', ['email'], unique=True)
    op.drop_column('personas', 'nombres')
    op.drop_column('personas', 'apellido_paterno')
    op.drop_column('personas', 'apellido_materno')
    op.drop_column('personas', 'correo_personal')
    op.drop_column('personas', 'created_at')
    op.drop_column('personas', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('personas', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('personas', sa.Column('correo_personal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('personas', sa.Column('apellido_materno', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('personas', sa.Column('apellido_paterno', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('personas', sa.Column('nombres', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_personas_email'), table_name='personas')
    op.drop_column('personas', 'email')
    op.drop_column('personas', 'apellido')
    op.drop_column('personas', 'nombre')
    # ### end Alembic commands ###
